# Generated by Django 5.2.3 on 2026-10-06 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chokies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merged_from', to='chokies.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('SENT', 'Sent to kitchen/bar'), ('BILLED', 'Billed'), ('PAID', 'Paid'), ('POSTED_TO_ROOM', 'Posted to room'), ('CANCELLED', 'Cancelled'), ('MERGED', 'Merged into another order')], default='OPEN', max_length=15),
        ),
    ]
